name: Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup go
        uses: actions/setup-go@v6.4.0
        with:
          go-version: '1.26'
          cache: false

      - name: Install yq
        run: go install github.com/mikefarah/yq/v4@latest

      - name: Install BusyBox
        run: |
          sudo apt-get update
          sudo apt-get install -y busybox

      - name: Run test
        run: 'tests/test.sh'
